#setting up the workflpw

name: Kyalo Workflow || Build and Deploy

#Controls when the workflow will run 
on:
    #trigger the workflow on push events
    push:
        branches: [ master ]
    #allows you to run this workflow manually from the actions tab
    workflow_dispatch:
        
jobs:
    build:
        #the type of runnner that the job will run on
        runs-on: self-hosted

        #setting up the matrix version
        strategy:
            matrix:
                node-version: [ 18 ]
        #steps represents a sequence of tasks that will be executed as part of the job
        steps:
            #checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: checkout
              uses: actions/checkout@v2
              with:
                presist-credentials: false

            #Run a single command using the runners shell
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}

            - name: Install & build
              run: |
                npm run build
                pm2 stop 0
                pm2 start 0
                pm2 save
                sudo systemctl restart nginx