#setting up the workflpw

name: Kyalo Workflow || Build and Deploy

#Controls when the workflow will run 
on:
    #trigger the workflow on push events
    push:
        branches: [ master ]
    #allows you to run this workflow manually from the actions tab
    workflow_dispatch:

    schedule:
        #cron syntax #run at 21:00 UTC every day which is 00:00 EAT Kenya Time(UTC+3)
        - cron: '0 21 * * *'

jobs:
    build:
        #the type of runnner that the job will run on
        runs-on: self-hosted

        #setting up the matrix version
        strategy:
            matrix:
                node-version: [ 18 ]
        #steps represents a sequence of tasks that will be executed as part of the job
        steps:
            #checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
            - name: checkout
              uses: actions/checkout@v2
              with:
                persist-credentials: false

            #Run a single command using the runners shell
            - name: Use Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v3
              with:
                node-version: ${{ matrix.node-version }}
            
            - name: Install Dependencies
              run: npm install

            
            - name: Check Last Deployment Status
              id: deployment_status
              run: |
                LAST_DEPLOY_FILE=".last_deploy_status"

                if [! -f "$LAST_DEPLOY_FILE" ]; then
                  echo "No previous deployment status found. Assuming success."
                  echo "deploy=true" >> $GITHUB_OUTPUT
                  exit 0
                fi

                LAST_STATUS=$(cat "$LAST_DEPLOY_FILE")
                CURRENT_STATUS=$(date +%s)

                DAYS_40=$((40 * 24 * 60 * 60))

                DIFF=$((CURRENT_STATUS - LAST_STATUS))

                if [ "$DIFF" -ge "$DAYS_40" ]; then
                  echo "40 days have passed since the last deployment. Proceeding with deployment."
                  echo "deploy=true" >> $GITHUB_OUTPUT
                else
                  echo "Deployment blocked. 40 days have not passed since the last deployment."
                  echo "deploy=false" >> $GITHUB_OUTPUT
                fi
              
            - name: Build Application
              if: steps.deployment_status.outputs.deploy == 'true'
              run: |
                npm audit fix --force
                npm run build
            
            - name: Restart Application
              if: steps.deployment_status.outputs.deploy == 'true' 
              run: |
                pm2 stop 0 | true
                pm2 start 0
                pm2 save

            - name: Update Last Deployment Status
              if: steps.deployment_status.outputs.deploy == 'true'
              run: |
                date +%s > .last_deploy_status

              #job status check if:success, always, failure can be used to check the status of the jobs
            - name: if Failure
              if: ${{ failure() }}
              run: |
                curl --request POSt \
                -- url https://api.github.com/repos/${{ github.repository }}/issues \
                --header 'authorization: Bearer ${{ secrets.GITHUB_TOKEN }}' \
                --header 'content-type: application/json' \
                --data '{
                  "title": "Issue Created due to workflow failure:
                    ${{ github.run_id }}",
                  "body": "Issue automatically Created by 
                  GITHUB Action workflow **${{ github.workflow }}**. \n\n due
                  to failure in run: _${{ github.run_id }}_."
                }'
                